### ISSUE TITLE
Support for 1.19.2?

### ISSUE THREAD

**Issue by C4ArtZ** [ruscalworld/fabric-exporter#7]
The latest version on Modrinth requires Minecraft 1.19(.0) so the server refuses to launch.

I noticed that the minecraft_version within the gradle.properties in this repository isset to 1.19.3. Do you think you could add a build for 1.19.2?

**Comment by ruscalworld** [comment]
Latest version (1.0.9) requires Minecraft 1.19.3. Modrinth displays that latest version supports only 1.19 due to build misconfiguration. I've just fixed this.

Supporting multiple Minecraft versions at once is a hard thing and I have no plans to provide support for outdated Minecraft versions. Now you could try to use FabricExporter 1.0.8 which was released before migration to 1.19.3, it would probably work also with 1.19.2.
